version: 2 # use CircleCI 2.0
jobs:
  pr_check:
    docker: # run the steps with Docker
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer # directory where steps will run 
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Validate AMI
          command: |
            packer validate \
            -var "aws_region=${AWS_REGION}" \
            -var "aws_access_key=${AWS_ACCESS_KEY_ID}" \
            -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}" \
            -var "source_ami=${SOURCE_AMI}" \
            -var "ssh_username=${SSH_USERNAME}" \
            -var "ami_users=${AMI_USERS}" \
            ubuntu-ami.json


  build:
    docker: # run the steps with Docker
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer # directory where steps will run
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Build AMI
          command: |
            echo $AWS_REGION
            packer build \
            -var "aws_region=${AWS_REGION}" \
            -var "aws_access_key=${AWS_ACCESS_KEY}" \
            -var "aws_secret_key=${AWS_SECRET_KEY}" \
            -var "ssh_username=${SSH_USERNAME}" \
            -var "subnet_id=${SUBNET_ID}" \
            -var "source_ami=${SOURCE_AMI}" \
            -var "ami_users=${AMI_USERS}" \
            ubuntu-ami.json

workflows:
  version: 2
  pr-check-workflow:
    jobs:
      - pr_check
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master